name: CI
on: push
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.74.2"

      - name: NPM install
        uses: actions/setup-node@v1
        working-directory: themes/blank/
        with:
          node-version: '10.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Compil css
        working-directory: themes/blank/
        run: node node_modules/postcss-cli/bin/postcss assets/css/styles.css -o static/css/styles.css

      - name: Build FR
        run: |
         hugo --minify
         echo "eskio.net" > public/CNAME

      - name: Pushes to another repository FR
        uses: cpina/github-action-push-to-another-repository@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.GH_TOKEN }}
        with:
          source-directory: 'public'
          destination-github-username: 'LavoWeb'
          destination-repository-name: 'Eskio'
          user-email: aurelien@lavoweb.net
